id = "trigger-system"
name = "Trigger System"
version = "0.1.0"
schema_version = 1
authors = ["nglmercer <nglmercer@gmail.com>"]
description = "Language support for Trigger System YAML rules"
repository = "https://github.com/nglmercer/trigger_system"

[language_servers.trigger-system-lsp]
name = "Trigger System LSP"
languages = ["Trigger YAML"]

[languages."Trigger YAML"]
name = "Trigger YAML"
grammar = "yaml"
path_suffixes = ["yaml", "yml", "trigger.yaml", "trigger.yml"]
line_comments = ["# "]
language_servers = ["trigger-system-lsp"]
tab_size = 2
hard_tabs = false

[grammars.yaml]
repository = "https://github.com/zed-industries/tree-sitter-yaml"
rev = "e5b85e7b8c4bd7c4c7c5b0f4615eb2e0105e1b6c"
